### ISSUE TITLE
ModuleAttributeError

### ISSUE THREAD

**Issue by mellody11** [qzp2018/MCLN#2]
Hi, thank you for sharing your great work.

In the file [mcln.py](https://github.com/qzp2018/MCLN/blob/a8e4fc621a65ae4393bb7b0b8d93681d8caff8a0/models/mcln.py#L431), line 431, I have encountered an error that `'MCLN' object has no attribute 'rel_encoder'`. It seems that the network lacks the module `rel_encoder`. 

Looking forward to your replay. Thank you.

**Comment by qzp2018** [comment]
Thank you for your carefulness, I update the file,  and you can try again.

**Comment by mellody11** [comment]
Thank you, the problem is solved, Howere, another problem occurs.

In file [mcln.py](https://github.com/qzp2018/MCLN/blob/36a24ec5b2634aede4f4f53a79b78e841a3c6c72/models/mcln.py#L78), line 78, The error is `ValueError: not enough values to unpack (expected 3, got 2)`. It seems that the return of MultiheadAttention is 2, but there are 3 values in the code.

Looking forward to your replay. Thank you.

**Comment by mellody11** [comment]
Hi, thank you for your attention, is the repository still being updated? There are still some problems in the latest version.

**Comment by mellody11** [comment]
Currently the problem I encountered is `ImportError: cannot import name 'NonDynamicallyQuantizableLinear' from 'torch.nn.modules.linear' (/data/liuxuexun/miniconda3/envs/mcln/lib/python3.7/site-packages/torch/nn/modules/linear.py)`

**Comment by qzp2018** [comment]
Hi, I tried in my version, it works. You can check in your file(/data/liuxuexun/miniconda3/envs/mcln/lib/python3.7/site-packages/torch/nn/modules/linear.py)  whether there exists NonDynamicallyQuantizableLinea

**Comment by mellody11** [comment]
Thank you, can you provide your Pytorch version? I use the version mentioned in the readme.md (Pytorch 1.9.0) and still encounter the error `AttributeError: 'Tensor' object has no attribute 'is_nested'`. This error may cause by the version of Pytorch.

Looking forward to your replay. Thank you.

**Comment by qzp2018** [comment]
Sorry that the version is'1.12.0+cu113', I update the READEME and related files. Please use the latest code and environment, I reconfigured the environment and ran all the code, there should be no other problems. :ambulance: :ambulance: :ambulance:

**Comment by mellody11** [comment]
Thank you, the code is successfully running now.
