### ISSUE TITLE
ModuleNotFoundError: No module named 'models.torch.utils'

### ISSUE THREAD

**Issue by RobinLiuZX** [qzp2018/MCLN#3]
> Traceback (most recent call last):
>   File "/mnt/sda/lzx/MCLN/train_dist_mod.py", line 19, in <module>
>     from main_utils import parse_option, BaseTrainTester
>   File "/mnt/sda/lzx/MCLN/main_utils.py", line 27, in <module>
>     from models import HungarianMatcher, SetCriterion, compute_hungarian_loss
>   File "/mnt/sda/lzx/MCLN/models/__init__.py", line 7, in <module>
>     from .mcln import MCLN
>   File "/mnt/sda/lzx/MCLN/models/mcln.py", line 11, in <module>
>     from .torch.nn import MultiheadAttention
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/__init__.py", line 1, in <module>
>     from .modules import *  # noqa: F403
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/modules/__init__.py", line 1, in <module>
>     from .module import Module
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/modules/module.py", line 12, in <module>
>     from ...utils.hooks import RemovableHandle
> ModuleNotFoundError: No module named 'models.torch.utils'
> Traceback (most recent call last):
>   File "/mnt/sda/lzx/MCLN/train_dist_mod.py", line 19, in <module>
>     from main_utils import parse_option, BaseTrainTester
>   File "/mnt/sda/lzx/MCLN/main_utils.py", line 27, in <module>
>     from models import HungarianMatcher, SetCriterion, compute_hungarian_loss
>   File "/mnt/sda/lzx/MCLN/models/__init__.py", line 7, in <module>
>     from .mcln import MCLN
>   File "/mnt/sda/lzx/MCLN/models/mcln.py", line 11, in <module>
>     from .torch.nn import MultiheadAttention
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/__init__.py", line 1, in <module>
>     from .modules import *  # noqa: F403
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/modules/__init__.py", line 1, in <module>
>     from .module import Module
>   File "/mnt/sda/lzx/MCLN/models/torch/nn/modules/module.py", line 12, in <module>
>     from ...utils.hooks import RemovableHandle
> ModuleNotFoundError: No module named 'models.torch.utils'
Is it possible that some files are missing from the **models.torch** directory?

**Comment by qzp2018** [comment]
Sorry that we rewrite the MultiheadAttention in the torch.nn, I upload the mcln_attention.py and import MultiheadAttention via relative paths, you can try whether it works.

**Comment by RobinLiuZX** [comment]
Thank you for your patient responses and corrections. I wish you success in your research and happiness in your work!

**Comment by RobinLiuZX** [comment]
> Traceback (most recent call last):
>   File "/mnt/sda/lzx/MCLN/train_dist_mod.py", line 353, in <module>
>     ckpt_path = train_tester.main(opt)
>   File "/mnt/sda/lzx/MCLN/main_utils.py", line 433, in main
>     self.train_one_epoch(
>   File "/mnt/sda/lzx/MCLN/main_utils.py", line 531, in train_one_epoch
>     end_points = model(inputs)
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
>     output = self._run_ddp_forward(*inputs, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
>     return module_to_run(*inputs[0], **kwargs[0])
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/sda/lzx/MCLN/models/mcln.py", line 527, in forward
>     bs_text_query, _,src_weight = self.swa_layers[i]( super_features[bs].unsqueeze(0).transpose(1,2).transpose(0,1),bs_text_query.transpose(0,1), attn_mask=attn_masks)#SWA模块
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/sda/lzx/MCLN/models/mcln.py", line 78, in forward
>     output, output_weight, src_weight = self.attn(query, k, v, key_padding_mask=None,attn_mask=attn_mask)  # (1, 100, d_model)
>   File "/home/ubuntu/anaconda3/envs/3D-STMN/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/sda/lzx/MCLN/models/mcln_attention.py", line 633, in forward
>     attn_output, attn_output_weights,src_weights = multi_head_attention_forward(
>   File "/mnt/sda/lzx/MCLN/models/mcln_attention.py", line 337, in multi_head_attention_forward
>     attn_output, attn_output_weights,src_weight = _scaled_dot_product_attention(q, k, v, attn_mask, dropout_p)
> ValueError: not enough values to unpack (expected 3, got 2)
I used the latest version of the code you provided, but I still encountered the aforementioned problem. Why is that?

**Comment by qzp2018** [comment]
I update the READEME and related files. Please use the latest code and environment, I reconfigured the environment and ran all the code, there should be no other problems. :see_no_evil: :see_no_evil: :see_no_evil:
