### ISSUE TITLE
I feel that there is an issue with the running efficiency of this code.

### ISSUE THREAD

**Issue by RobinLiuZX** [qzp2018/MCLN#4]
I am running the code in a dual NVIDIA RTX 3090 environment, but the time to train one epoch has increased from around 2 hours to now over 10 hours, and it still hasn't finished training one epoch. Could you please tell me why this is happening?

**Comment by qzp2018** [comment]
This is strange, it takes 25minutes to train one epoch with 4 3090 GPUs, so around one hour with 2 3090 gpus is normal but not 2 hours.

**Comment by qzp2018** [comment]
I tried on the official code and ran successfully. It takes 26 minutes to train one epoch with 4 3090 GPUs, and 48 minutes with 2 3090 GPUs. You may check whether your data is correctly organized.

**Comment by RobinLiuZX** [comment]
Ok, thanks!

**Comment by Starboy-at-earth** [comment]
How long time does the algorithm take to train on ReferScan using two RTX 3090s?

**Comment by qzp2018** [comment]
> How long time does the algorithm take to train on ReferScan using two RTX 3090s?

About 2.5 days
