### ISSUE TITLE
ModuleNotFoundError: No module named 'segmentator.csrc.build.libsegmentator'

### ISSUE THREAD

**Issue by zaiquanyang** [qzp2018/MCLN#7]
After I build the segmentator, I meet an error when runing prepare_data_inst.py. What could be the reason of this?

File "/mnt/MCLN/scannetv2/segmentator/main.py", line 2, in <module>
    from .csrc.build.libsegmentator import segment_mesh as segment_mesh_fn, segment_point as segment_point_fn
ModuleNotFoundError: No module named 'segmentator.csrc.build.libsegmentator'

**Comment by Wang-hui-001** [comment]
Hello, has this issue been resolved? I have the same problem as you. If it has been resolved, could you please share the solution?
